global:
  smtp_smarthost: 'smtp:25'
  smtp_from: 'alekseyda_92@mail.ru'
route:
  receiver: example-email
  group_by: [alertname]
receivers:
 - name: example-email
   email_configs:
    - to: 'alekseyda_92@mail.ru'